# Generated by Django 4.0.4 on 2022-04-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='check_in',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='check_out',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='customer_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
