# Generated by Django 4.0.4 on 2022-04-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_alter_rooms_check_in_alter_rooms_check_out_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='check_in',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='check_out',
            field=models.DateField(null=True),
        ),
    ]
